import type { Project, ArchiveCapture } from './supabase';

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: 'fb-netbond',
    title: 'NetBond Advanced',
    role: 'Lead Product Designer',
    client: 'AT&T',
    summary: 'Electron desktop app for managing enterprise cloud router infrastructure. 619 files, multi-panel UI with real-time network topology, provisioning workflows, and SDCI circuit management.',
    tags: ['Electron', 'React', 'TypeScript', 'Network UX', 'AT&T'],
    image_url: '',
    year: '2024',
    order_index: 1,
    featured: true,
    situation: null,
    task: null,
    action: null,
    result: null,
    gallery_urls: [],
  },
  {
    id: 'fb-pve',
    title: 'Product Value Engine',
    role: 'Lead Product Designer',
    client: 'AT&T',
    summary: 'AI-powered sales platform that generates product narratives, value propositions, and competitive positioning for AT&T enterprise offerings. Claude-backed reasoning engine.',
    tags: ['AI', 'Claude API', 'React', 'Sales Tools', 'AT&T'],
    image_url: '',
    year: '2025',
    order_index: 2,
    featured: true,
    situation: null,
    task: null,
    action: null,
    result: null,
    gallery_urls: [],
  },
  {
    id: 'fb-network-designer',
    title: 'Network Visual Designer',
    role: 'Lead Product Designer',
    client: 'AT&T',
    summary: 'Interactive drag-and-drop topology builder for designing AT&T cloud network architectures. Canvas-based with node configuration, edge routing, simulation, and PDF export.',
    tags: ['React', 'Canvas', 'Network UX', 'Three.js', 'AT&T'],
    image_url: '',
    year: '2024',
    order_index: 3,
    featured: true,
    situation: null,
    task: null,
    action: null,
    result: null,
    gallery_urls: [],
  },
  {
    id: 'fb-roots',
    title: 'Roots — Williams Family Tree',
    role: 'Designer & Developer',
    client: 'Personal',
    summary: 'Full-stack genealogy platform. 55 commits, 30 pages, 38 APIs, 170+ features. Next.js 16, Supabase, Claude AI narrative generation, Stripe billing, interactive family tree visualizations.',
    tags: ['Next.js', 'Supabase', 'Claude AI', 'Stripe', 'Full-Stack'],
    image_url: '',
    year: '2025',
    order_index: 4,
    featured: true,
    situation: null,
    task: null,
    action: null,
    result: null,
    gallery_urls: [],
  },
  {
    id: 'fb-conscious-shell',
    title: 'conscious-shell',
    role: 'Designer & Developer',
    client: 'Self',
    summary: 'This portfolio. Blade Runner 2049 aesthetic, Three.js city grid, AI agent battle, temporal archive, Voight-Kampff test, Supabase-backed. 25 years of design history in a single scroll.',
    tags: ['React', 'Three.js', 'Vite', 'Supabase', 'Portfolio'],
    image_url: '',
    year: '2025',
    order_index: 5,
    featured: true,
    situation: null,
    task: null,
    action: null,
    result: null,
    gallery_urls: [],
  },
];

export const FALLBACK_ARCHIVE: ArchiveCapture[] = [
  {
    id: 'arc-2000',
    year: 2000,
    timestamp_raw: '20000601120000',
    captured_at: '2000-06-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'early-web · table layouts · marquee tags',
    order_index: 1,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2004',
    year: 2004,
    timestamp_raw: '20040901120000',
    captured_at: '2004-09-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'flash era · motion graphics · skip intro',
    order_index: 2,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2009',
    year: 2009,
    timestamp_raw: '20090101120000',
    captured_at: '2009-01-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'wordpress era · rounded corners · gradients',
    order_index: 3,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2014',
    year: 2014,
    timestamp_raw: '20140601120000',
    captured_at: '2014-06-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'responsive era · flat design · bootstrap',
    order_index: 4,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2019',
    year: 2019,
    timestamp_raw: '20190101120000',
    captured_at: '2019-01-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'react era · component systems · dark mode',
    order_index: 5,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2022',
    year: 2022,
    timestamp_raw: '20220601120000',
    captured_at: '2022-06-01T12:00:00Z',
    original_url: 'http://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'jamstack era · vite · tailwind · headless',
    order_index: 6,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
  {
    id: 'arc-2025',
    year: 2025,
    timestamp_raw: '20250101120000',
    captured_at: '2025-01-01T12:00:00Z',
    original_url: 'https://conscious-shell.com',
    wayback_url: '',
    embed_url: '',
    era_label: 'blade runner era · three.js · ai agents · supabase',
    order_index: 7,
    screenshot_url: '',
    custom_screenshot_url: '',
  },
];
