/*
  # Create linkedin_recommendations table

  Real LinkedIn recommendations received, parsed from LinkedIn data export.
  Used by WebDossier (testimony category) and VKInterview (corroboration block).

  - Public read access (RLS) for portfolio display.
*/

CREATE TABLE IF NOT EXISTS linkedin_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recommender_name text NOT NULL,
  recommender_role text NOT NULL DEFAULT '',
  recommendation_text text NOT NULL,
  excerpt text NOT NULL DEFAULT '',
  relationship text NOT NULL DEFAULT 'colleague',
  traits_signal jsonb NOT NULL DEFAULT '[]'::jsonb,
  given_date date NOT NULL,
  order_index int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE linkedin_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read linkedin_recommendations"
  ON linkedin_recommendations
  FOR SELECT
  TO anon, authenticated
  USING (true);

INSERT INTO linkedin_recommendations (recommender_name, recommender_role, recommendation_text, excerpt, relationship, traits_signal, given_date, order_index) VALUES
('Stephanie Bartman', 'UX/UI Designer · PetSmart', 'I was fortunate to have Micah as my mentor during the Career Services portion of my learning at Designlab. His encouragement and guidance were invaluable as I navigated the daunting process of job applications and interviews. Micah has an incredible ability to instill confidence when it’s needed most. Whether reviewing resumes or preparing for interviews, he consistently brings positivity and a genuine belief in others’ potential to every conversation. I can’t recommend Micah highly enough to anyone fortunate enough to work with him!', 'I was fortunate to have Micah as my mentor during the Career Services portion of my learning at Designlab.', 'mentee', '["empathy"]'::jsonb, '2024-12-03', 0),
('Sridhar Narahari', 'Product Management · Juniper Networks', 'Micah is an experienced design leader who is a gem when it comes to collaboration. He has a well-honed design toolkit, works backward from the customer-centric, and is data-driven. He is also able to make his thoughts and recommendations understandable to a diverse set of audiences spanning different disciplines. He has been an invaluable asset for all of our projects that involve experience simplification.', 'Micah is an experienced design leader who is a gem when it comes to collaboration.', 'colleague', '["logic"]'::jsonb, '2024-09-06', 10),
('Estefania Tarantini', 'Airbnb Superhost · Self-employed', 'Micah was my mentor at CareerFoundry''s UI Design course. He''s very talented and great with the little details and a unique way of teaching them. He helped me immensely, providing constructive feedback that improved my UI skills significantly. His mentorship has left a lasting impact on me, and I am forever grateful for his guidance.', 'Micah was my mentor at CareerFoundry''s UI Design course.', 'mentee', '["empathy"]'::jsonb, '2024-01-24', 20),
('Amanda Smolik', 'UX / UI Designer · VolunteerMatch', 'Micah was my mentor during my UI boot camp at Career Foundry. He was a great mentor and always answered all of my questions. Micah gave me good advice and recommendations for my projects. He is very nice to chat with and knows what he is talking about when it comes to UI design. I am glad to have worked with him and have a lifelong connection.', 'Micah was my mentor during my UI boot camp at Career Foundry.', 'mentee', '["empathy"]'::jsonb, '2023-07-12', 30),
('Bryan Patrick', 'UX / UI Designer · Terra Seco Solutions', 'I was fortunate to have Micah as my mentor when I first got into UX design. It’s natural to have some degree of doubt when you’re transitioning to a new field, but he helped assuage my concerns by imparting useful knowledge when it came to a variety of aspects of UX design and doing so with a sense of empathy and passion. He has an abundance of interesting and relevant experiences to draw from when working with students and I’m appreciative of the time I had to interact with him. He was instrumental in leading me to the necessary tools that can increase the success and comfort a UX designer experiences. He especially emphasized the power of utilizing particular design tools and helped advance my designs considerably. Moreover, he provided useful and positive feedback on my case study in a way that gave me actionable advice, but also an increased sense of confidence.', 'I was fortunate to have Micah as my mentor when I first got into UX design.', 'mentee', '["empathy","darkness"]'::jsonb, '2022-07-05', 40),
('Ana Ortiz', 'Graphic/UI Designer · National LED', 'Micah was my assigned mentor when I started my journey in UX/UI design. Little did I know that I had the best mentor. As you can imagine stepping out of one career profession and into a completely new one was a bit of a an emotional rollercoaster. Micah was not only an amazing, professional, experienced, talented and empathic senior ux designer but he lead me through my journey. He guided me through all my CareerFoundry experiences of joy, fear and doubt. He gave constructive feedback to help me improve my overall skills as a ux designer. He guided me through all the steps and especially emphasised how to become my own unique ux designer and to be proud of that. He is genuinely and authentically doing one of many things he is great at and enjoys. I will always be grateful for your guidance.', 'Micah was my assigned mentor when I started my journey in UX/UI design.', 'mentee', '["empathy","creativity"]'::jsonb, '2022-04-30', 50),
('Jennifer Liu', 'Product Designer · Kroger Technology & Digital', 'Micah was my mentor through Career Foundry''s User Experience Design Boot Camp. I was embarking on a tremendously daunting career change - classical violinist to product design. On day 1, Micah was curious about who I was; a human who wanted to contribute something meaningful. We bonded over our shared high values, which helped center and guide my progress. On a technical level, Micah was so willing and patient to experiment and tinker with the smallest of details. He has an insanely detailed eye, paired with modern and clean aesthetics. And zoomed out, Micah would endlessly share resources and help me network. Micah heard my concerns, worries, and curiosities, no matter the weight of them. He''s a whole human, a rare gem of a person who anyone would be lucky to share time with.', 'Micah was my mentor through Career Foundry''s User Experience Design Boot Camp.', 'mentee', '["empathy"]'::jsonb, '2022-04-27', 60),
('Mackenzie Curran', 'Director of User Experience · The Office of Experience', 'Micah was my UX Design mentor, and he is truly one of most insightful designers out there. Throughout our mentorship, he was an incredible source of inspiration and guidance - challenging me to dig deeper, encouraging me to reach my potential, enlightening me with his UX expertise, and engaging in thoughtful conversations about the work and processes. Micah went above and beyond to get to know me on a human level, and through that, helped me discover the unique aspects that elevate me as a designer. He is wise, he is thoughtful, and he cares. Micah was an incredible mentor, and anyone who has the privilege of working with him - whether it be through design or mentorship - will be lucky to have one of the best.', 'Micah was my UX Design mentor, and he is truly one of most insightful designers out there.', 'mentee', '["empathy","creativity"]'::jsonb, '2022-04-01', 70),
('Sarah McCormick', 'Assistant Manager/Apprenticeship Coordinator · Left Foot Charley', 'Micah was my mentor at CareerFoundry for the UX Design Certification.  He did a great job making me comfortable with speaking to him about all of my projects!  He has an amazing eye for detail and a great way of teaching others how to see those same details!  He takes the time to connect with his students and make sure that they are getting all that they need out of their classes even if that means extra time and research on his part.    He also did a great job challenging me to go above and beyond the basic requirements of the class so that I could create the best portfolio possible!  He truly is a great mentor and teacher.', 'Micah was my mentor at CareerFoundry for the UX Design Certification.', 'mentee', '["empathy"]'::jsonb, '2021-08-18', 80),
('Craig Lawrence', 'Partner · Energy Transition Ventures', 'Micah is a spectacular designer, and a spectacular human being. We worked closely together for several years at Treverity, bringing humanity and light to the cold, cold world of electric and gas utility software - with me as product manager, Micah as all-things UI/UX. Micah''s design chops are superb - he produced beautiful, engaging, and usable software, with a keen understanding the user''s journey, and an ability to get inside their heads. And the capacity to translate complex requirements into beauty. Micah coined the therm "Human Integration" to describe what we were trying to do - to go beyond Systems Integration and put the person at the center of their work, and help them do their job better. I would highly recommend Micah for any user experience and design leadership position, and I will most happily work with him again if I get the chance.', 'Micah is a spectacular designer, and a spectacular human being.', 'colleague', '["darkness"]'::jsonb, '2020-07-10', 90),
('Michael Tinglin', 'Senior Director of Product Design & Research · Upbound Group', 'I had the pleasure of working with Micah on several high profile mobile projects that were cross platform, multi regional with a large list of requirements. His attention to detail, his gregarious and outgoing personality and his can do attitude lead to some great design thinking sessions and creative solutions. His ability to move deftly between UX Architecture, Design, Animation and Prototyping made him an asset to the team. He would be a great addition to any organization and I would love the opportunity to work with him again in the future.', 'I had the pleasure of working with Micah on several high profile mobile projects that were cross platform, multi regional with a large list of requirements.', 'peer', '["creativity"]'::jsonb, '2018-04-07', 100),
('Lara Moritz', 'Director of Business Systems · Lila Sciences', 'Micah is a consummate professional and joy to work with. He is very personable and gives you 110%.  You can trust him to deliver on-time, be professional and ask questions if needed.  You can set him loose on a project and know that it will be delivered with the highest quality. We need more like Micah in this business.', 'Micah is a consummate professional and joy to work with.', 'peer', '["empathy"]'::jsonb, '2013-08-20', 110),
('Tom Huynh', 'Senior Frontend Developer · Spark Energy', 'I worked with Micah on a collaborative project that involved a lot of future thinking of where BI Portals are headed today. He was responsible for the creative research that we presented to the client, as well as taking a visual design direction that I created for a conceptual BI Portal and taking it to the next level. Micah is an extremely passionate and creative individual, and it was a pleasure to work with Micah. Definitely looking forward to collaborating with Micah again.', 'I worked with Micah on a collaborative project that involved a lot of future thinking of where BI Portals are headed today.', 'colleague', '["creativity","honesty"]'::jsonb, '2013-08-02', 120),
('Josyanne Pierrat', 'Co-présidente patronale du conseil d’administration · Camo-Route', 'I had the opportunity to work with Micah on an multilingual web project. His extensive experience, personable nature and ability to connect multiculturally made him a key leadership element early on in the process. Micah is as adept at understanding people as he is understanding technology, and his innate knack at ''getting'' fluid project dynamics makes him a truly unique experience professional.', 'I had the opportunity to work with Micah on an multilingual web project.', 'colleague', '["empathy"]'::jsonb, '2013-02-21', 130),
('Doug Sanders', 'VP, Strategic Growth · Meriton', 'Micah not only made my job easier here at The Richards Group, he made me a smarter person in the digital space as a result. Through his work, he continues to be a personal inspiration to have more focus in the world of digital communication. Micah is incredibly smart, a buttoned-up presenter, ahead of the curve of almost all digital trends and consistently works to help drive our client''s business. It''s hard to find a team member that brings a perfect blend of strategy, experience and creativity to the table - Micah delivers on all of that and more.', 'Micah not only made my job easier here at The Richards Group, he made me a smarter person in the digital space as a result.', 'peer', '["creativity","darkness"]'::jsonb, '2012-11-07', 140),
('Tali Swann-Sternberg', 'Staff User Experience Research Manager · Google', 'Micah is a dedicated and talented UX professional. He is passionate about creating exemplary digital solutions and has the knowledge and experience to deliver. He is an avid reader of all that is new and interesting in UX, and he actively shares this knowledge with colleagues. On top of this, it is a pleasure working with Micah! He is always ready to discuss the pros and cons of various strategies or designs and work with you to determine the best solution. I hope I will get to work with him again in the future.', 'Micah is a dedicated and talented UX professional.', 'colleague', '["logic","darkness"]'::jsonb, '2012-09-06', 150),
('Keleigh Milliorn', 'Principal UX Designer · Fidelity Investments', 'Micah is truly one of a kind. He''s incredibly smart and builds his knowledge base by constantly researching or reading about the latest and greatest in the UX field.  His use of language is professional but clear, and he imparts his wisdom in the most inclusive way, often attributing his own ideas to others in the group if they planted even the smallest of seeds. He''s passionate about his work and his solutions are second to none. In addition to all that, he''s genuinely a nice guy.    I loved working with Micah and enthusiastically recommend him. If you can get him, do it now!', 'Micah is truly one of a kind.', 'colleague', '["empathy","darkness"]'::jsonb, '2012-09-05', 160),
('Arie Stavchansky', 'Founder · Dataclay', 'Micah is one of the most detail oriented UX designers I''ve worked with.  He has an excellent sense of gestalt, and is very cognizant about the human experience as related to interactive media.  It is so rare to find a designer who cares about observing how people interact with things, and capable of translating those observations into creative solutions.  Micah thinks through so many facets of the design problems presented to him such that it is difficult to find any gaps left in his work.  When a critique is presented to him he takes it in the most professional and mature fashion I have ever witnessed.  As creative director I was confident that Micah would listen closely to all my critiques and respond with a highly creative solution.    From a technical standpoint, he has such a mastery of his digital tool sets, that I was never found myself hand holding.  He just gets things done, and doesn''t let his tools get in the way of his vision.  His hard deliverables show that he is a craftsman who reflects as he creates.  This gives his work the mark of superior workmanship.    Aside from the work itself, he is a fun person to collaborate with.  I looked forward to each and every conversation we had as he is very thoughtful on a number of topics related to design practice and industry.  He''s got a great sense of humor which can only improve work.    If you have the chance to work with him, take it.  The results you will get are extraordinary.', 'Micah is one of the most detail oriented UX designers I''ve worked with.', 'peer', '["empathy","creativity","honesty","darkness"]'::jsonb, '2011-09-13', 170),
('David Moskovic', 'Co-Founder & Managing Partner · devTonic', 'Micah is not just a solid UI designer and all around user experience expert, he taps into a wide and deep pool of knowledge and experience that go beyond the mere mechanics of designing interfaces. He has what it takes to design for human beings (that creative spark, call it what you want). Plus Micah is just great to be around. I look forward to working with him on many more projects.', 'Micah is not just a solid UI designer and all around user experience expert, he taps into a wide and deep pool of knowledge and experience that go beyond the mere mechanics of designing interfaces.', 'peer', '["creativity","darkness"]'::jsonb, '2011-07-11', 180),
('Stephanie Mahaffey', 'CEO and Founder · Hip Peas Inc', 'Micah is one of the most creative people I''ve ever had the pleasure to work with.  He is not only an expert at "thinking outside the box", he is also a consummate professional who is easily able to adapt and direct his creativity so as to most benefit the project at hand.  I would definitely seek out Micah in the future should my business needs require his expertise.', 'Micah is one of the most creative people I''ve ever had the pleasure to work with.', 'peer', '["creativity","honesty"]'::jsonb, '2011-06-28', 190),
('Michael Breen', 'Member Board of Directors · Pecan Street Inc.', 'Micah has a unique and valuable perspective that he is able to integrate into client service.   His user experience finesse is the result of careful human observation and focused listening skills.    The combination of patient listening and ambitious engagement is winning.', 'Micah has a unique and valuable perspective that he is able to integrate into client service.', 'peer', '["empathy"]'::jsonb, '2011-06-27', 200),
('Tim Biggio', 'VP Americas & Legal Ops · Precisely', 'Vision. Creativity. Thought provoking. Intelligent. Fun. Diverse.    I had the privilege of working with Micah while our paths crossed at Broadlane. He is one of those rare gems that in addition to his amazing creativity and ability to make great visual products (often based on mere vague ideas of what is needed), he remains positive and upbeat even in the face of chaos. If you have not yet engaged Micah in a conversation, I urge you to do so. His portfolio of work can show you his results and output, but only by talking with him can you see how his creative mind works to turn a vision into reality. I enjoyed the opportunity to work with Micah and would do so again any time.', 'Vision. Creativity. Thought provoking.', 'peer', '["empathy","creativity"]'::jsonb, '2011-06-26', 210),
('Brienna Becker', 'Director of Recruiting · Everest Search Partners LLC', 'Micah has a keen sense of design. A great listener that translates vision into simple, elegant logos and websites. His dedication to cash-strapped entrepreneurs is proof of his dedication to great ideas and the local start-up community. If Micah is to be judged by the amount of sweat equity he provides to this community, he is one sweaty guy indeed. :)', 'Micah has a keen sense of design.', 'peer', '["empathy"]'::jsonb, '2011-04-29', 220),
('Linda Huval', 'Executive Assistant · Broadlane', 'Micah is an exceptional person.  He has wonderful creative and design skills that far surpass anyone that I have ever known in my working career.  He has fabulous people skills as well.  He is always willing to give you his undivided attention when listening to your thoughts or ideas.  He offers constructive feedback and/or criticism.  He is a joy to be around and to work with.  He would definitely be an asset to any company or organization.', 'Micah is an exceptional person.', 'colleague', '["empathy","creativity"]'::jsonb, '2010-12-08', 230),
('Patricia Cmielewski, MBA, MSW', 'Clinician · Tampa Bay Area Counseling', 'Micah offers the ideal blend of strategic and executional capabilities, which he aptly applies to both consumer and busienss marketing. He is a strong contributor who conceptualizes based on the customer and in proper context of the medium. His talent combined with his leadership are highly valued attributes.', 'Micah offers the ideal blend of strategic and executional capabilities, which he aptly applies to both consumer and busienss marketing.', 'colleague', '["logic"]'::jsonb, '2010-11-17', 240),
('Casey Ausherman', 'Senior Vice President, Enterprise Marketing · Vizient, Inc', 'I have had the pleasure of working with Micah for three years at The Broadlane Group. He is an incredible asset to any team with his innovative and creative ideas. Micah has a broad scope of knowledge and is well versed on the latest technology and trends that make him an invaluable team member. One of his many great attributes is his contributions in creating competitive, innovative, and forward thinking solutions for the projects he is involved in.', 'I have had the pleasure of working with Micah for three years at The Broadlane Group.', 'peer', '["creativity","darkness"]'::jsonb, '2010-11-09', 250),
('Lauren Heath', 'Account Executive · Martin Retail Group', 'I have had the pleasure of working with Micah at The Broadlane Group.  He is a very unique and intelligent professional.  He is a proven creative leader with a phenomenal design aesthetic.  He brings a vision and passion to the business.  On a daily basis Micah works to improve himself as well as the team he is working with.  He is an asset to anyone’s creative team.', 'I have had the pleasure of working with Micah at The Broadlane Group.', 'colleague', '["creativity"]'::jsonb, '2010-10-07', 260),
('Jon David Poteet, MBA', 'President · Ironclad Capital Partners', 'As a creative talent, Micah is unrivaled. His ability to morph cryptic, abstract concepts into tangible, easily digested (and effective) constructs exceeds the traditional artist or creative. He posesses an innate knack...and one that has been honed over years of experience. I would stake my reputation on the fact that one would be hard-pressed to find a more gifted creative director that weaves both concept development and accomplished artistic vision so effortlessly.', 'As a creative talent, Micah is unrivaled.', 'peer', '["creativity","honesty","darkness"]'::jsonb, '2010-10-06', 270),
('Geoff German', 'Executive Creative Director · Squires&Co', 'Micah is one of the hardest working individuals I''ve had the pleasure of working with. The passion he exhibits for his work is undeniable. He has a very clearly delineated vision for his company''s brand and an excellent understanding of how it applies throughout various media. Micah doesn''t fit squarely into any particular "niche." He has a very broad knowledge of many forms of visual communication and seems to thrive on learning more and more about his trade. He takes his work very seriously and has a vast vocabulary of knowledge he taps into communicate his thoughts and ideas thoroughly and effectively. A collaborator in the truest sense, he enjoys the process of creation and watching the projects he curates find great success. These qualities plus the fact that he is a determined and motivated leader make him someone that I would recommend very highly.', 'Micah is one of the hardest working individuals I''ve had the pleasure of working with.', 'peer', '["darkness"]'::jsonb, '2010-09-21', 280),
('Damon Damele', 'Product and Strategy Consultant', 'Micah is one of the most creative people I have ever had the pleasure of working with.  He has a wealth of branding, marketing, and web design knowledge and the people skills to put it all to use.  A consummate team player, Micah is always willing to lend a hand or contribute ideas to a project.  I am constantly impressed by the quality of his work and his dedication to his role.  I would recommend Micah without hesitation.', 'Micah is one of the most creative people I have ever had the pleasure of working with.', 'colleague', '["creativity","darkness"]'::jsonb, '2010-07-30', 290),
('Laura Root', 'Executive Director of Brand & Creative Services, Marketing & Communications at Texas A&M University · Texas A&M University', 'Micah has the rare talent of being a strong creative problem-solver, a multi-tasker and an efficient project manager all in one. After working with him on several projects, I’ve come to appreciate his professionalism, work ethic, and attention to detail. Micah works tirelessly as the creative lead on multiple projects at Broadlane, providing leadership and guidance and meeting tight deadlines, all while maintaining a cheerful and professional attitude. He seems to handle multiple irons in the fire with grace, able to efficiently delegate while retaining his creative focus and passion. Micah is an essential creative liaison to our team, and is an invaluable asset to Broadlane as the champion of the company brand.', 'Micah has the rare talent of being a strong creative problem-solver, a multi-tasker and an efficient project manager all in one.', 'peer', '["creativity"]'::jsonb, '2010-05-09', 300),
('Roger Nolan', 'Chief Retirement Officer · CEO of Retirement', 'Creative.  There is no better way to summarize the person, his best attribute and his work.  Micah Boswell certainly brings more to the table than creativity - but it is his creativity that keeps you engaged.  An entrepreneur at heart and in application - Micah has the unique ability to open your eyes to the many possibilities while maintaining the candor necessary to properly evaluate and act on them.  I both enjoyed and appreciated working with Micah at Broadlane and would welcome/recommend an opportunity to work with Micah in the future.', 'Creative. There is no better way to summarize the person, his best attribute and his work.', 'peer', '["creativity"]'::jsonb, '2010-01-24', 310),
('Yoko Nakano', 'Senior Director of Product Management · Everplans', 'Working with Micah has been a true joy. In an aggressive timeframe, he delivered high-quality work in a timely manner while contributing to keep the energy and momentum of the team. As a Information Architect, it was one of the smoothest and most satisfying collaboration with a graphic designer. It was evident that Micah is well-versed in the art of visual communication that achieves real results.', 'Working with Micah has been a true joy.', 'peer', '["logic"]'::jsonb, '2010-01-23', 320),
('Steve Scott, PMP, CSM', 'Senior Project Manager · Blend', 'I''ve worked with Micah at two Healthcare related companies now in 7 years.  He''s always been a valuable partner and the basis of knowledge when I come to him with my IT questions.  He''s got integrity, is personable with clients, and knows his business.  I look forward to continue working with Micah.', 'I''ve worked with Micah at two Healthcare related companies now in 7 years.', 'colleague', '["honesty","darkness"]'::jsonb, '2009-12-22', 330),
('Jay Staton', 'Owner · BANDHOLE MEDIA LLC', 'Micah is an outstanding graphic designer who possesses the ability to truly understand the client''s needs and help translate that into practical terms for the development team.', 'Micah is an outstanding graphic designer who possesses the ability to truly understand the client''s needs and help translate that into practical terms for the development team.', 'colleague', '["empathy"]'::jsonb, '2009-12-21', 340),
('Wanda Roe, MBA', 'Omnichannel Marketing Operations Manager · Tata Consultancy Services', 'Micah is an exceptional graphic designer and is skilled in the art of building websites. His work ethic and ability to learn new things quickly made him a valuable asset. Micah''s delightful personality and sense of humor made him a pleasure to work around. I would highly recommend him for website design.', 'Micah is an exceptional graphic designer and is skilled in the art of building websites.', 'colleague', '["empathy"]'::jsonb, '2009-12-20', 350),
('🎯 Carri Craver', 'UX Design Manager · Take Command Health', 'Working with Micah was a pleasure.  He was able to listen to various different groups discuss their creative perspective and then design something that had a look that stood out and was spot on for the target market.  His work was high quality and he delivered quickly.      In addition, he was great in handling some chaos on our end.  And lastly he was simply enjoyable to work with.  Very positive attitude.  I would work with him again in a heartbeat.', 'Working with Micah was a pleasure.', 'colleague', '["empathy","creativity"]'::jsonb, '2009-03-26', 360),
('Ed Swierenga', 'VP, Supply Chain Optimization Services · MedAssets (now Vizient)', 'Micah brings an exceptional level of intellect and ingenuity to every project that he works on. His ability to blend cutting edge technology with artistic creativity makes him a valuable and highly sought after team member.  His people skills and problem solving expertise are of the highest caliber.', 'Micah brings an exceptional level of intellect and ingenuity to every project that he works on.', 'peer', '["creativity","darkness"]'::jsonb, '2009-02-04', 370),
('Mike Melton', 'Vineyard Manager · Warren Run Vineyard', 'Micah is an amazing artist and designer who incorporates the needs of multiple stakeholders at Broadlane. His timely responsiveness keeps projects on track and makes everyone look good.', 'Micah is an amazing artist and designer who incorporates the needs of multiple stakeholders at Broadlane.', 'colleague', '["empathy"]'::jsonb, '2009-01-07', 380),
('Traci Grover (Niehaus)', 'Health Insurance Broker · Vital Insurance Company', 'Micah is a genuine user experience specialist.  UX methods and processes are key elements, but without the innate ability to empathize with the target market, user experience expertise is useless.  Micah''s ability to empathize with the user is a natural trait, and coupled with the science of UX strategy, Micah is uniquely equipped to help people communicate their message to their intended audiences.  Micah is extremely talented and intelligent yet very down to earth and can relate to everyone.', 'Micah is a genuine user experience specialist.', 'colleague', '["empathy"]'::jsonb, '2008-12-01', 390),
('Christi Beard', 'Director, Global Marketing Campaigns, Integrated Marketing · Cisco', 'Micah Boswell is adept at deciphering a proposed marketing message and need and skillfully working to identify the approach that will yield the best result.  From his graphic design capabilities -- Web graphics, online interfaces, logos and advertisements -- to his technological and programming savviness, Micah is able to deliver the best solution for all marketing requests.  Couple his skill set with his amicable and client service oriented demeanor, and you have a winning combination.', 'Micah Boswell is adept at deciphering a proposed marketing message and need and skillfully working to identify the approach that will yield the best result.', 'peer', '["logic"]'::jsonb, '2008-08-11', 400),
('Lisa Carr', 'Group Strategy Director // Associate Creative Director · Accenture Song', 'Micah combines two personality strengths to approach business problems – first, he has a masterful knack for understanding people and learning to communicate an idea in their language. Second, he’s great at conceptualizing elegant solutions to thorny communication problems. Most often, it’s in the visual realm, but he has the ability to create simple solutions that work across other realms as well. In other words, Micah isn’t “just” a designer. He’s a communications maverick. Catch him if you can.', 'Micah combines two personality strengths to approach business problems – first, he has a masterful knack for understanding people and learning to communicate an idea in their language.', 'peer', '["empathy"]'::jsonb, '2007-10-10', 410),
('Karen Kramer', 'VP, Internal Communications · Keurig Dr Pepper Inc.', 'Micah is an exceptional designer with a keen ability to turn the vaguest concepts or ideas into reality. I have been most impressed with the style and professionalism he brings to every project. His attention to detail, his talent and his dedication to graphic standards have brought a new level of consistency and artistry to the company''s print and Web materials.', 'Micah is an exceptional designer with a keen ability to turn the vaguest concepts or ideas into reality.', 'peer', '["empathy"]'::jsonb, '2006-11-28', 420),
('Lisa Carr', 'Group Strategy Director // Associate Creative Director · Accenture Song', 'Micah is an online pioneer from way back (featured in an Apple commercial, no less) who excels at creating compelling, visually appealing, user-centered solutions. It''s not just about the design (or the content) -- it''s about the total experience. He''s an inspiring and fascinating guy to work with.', 'Micah is an online pioneer from way back (featured in an Apple commercial, no less) who excels at creating compelling, visually appealing, user-centered solutions.', 'peer', '["empathy"]'::jsonb, '2004-07-05', 430);
